version: '3.5'

services:
  db:
    container_name: kosmetica
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    image: postgres